### ISSUE TITLE
Task Metadata import / sync

### ISSUE THREAD

**Issue by FlohGro-dev** [FlohGro-dev/Craftist#16]
the crosslinked or imported tasks should sync metadata from / to todoist

possible metadata:
- due date
- labels
- (projects)

metadata should be included in the same block but must not be synced back to todoist 

related to #14; #13

**Comment by WillPlatnick** [comment]
Would this import indented tasks as subtasks?

**Comment by FlohGro-dev** [comment]
No - this is just regarding the "metadata" of single tasks.

Subtasks is another think (#25 )
Or did I misunderstood you?

**Comment by WillPlatnick** [comment]
Ahh, that ticket was for importing, so I didn't know if it was covered there. I'm thinking in Craft, if I do this

```
[ ] Task
     ( ) Subtask
```

And then click 'Crosslink Open Tasks', it would create subtask as a subtask of Task in Todoist, just like how it imports today.

**Comment by FlohGro-dev** [comment]
what you describe is covered in this issue: #26

**Comment by FlohGro-dev** [comment]
done on #14
