### ISSUE TITLE
Import today tasks fails, all task import works

### ISSUE THREAD

**Issue by gulyasm** [FlohGro-dev/Craftist#56]
**Describe the bug**
After adding the API key, I tried to import today tasks. In Todoist, there are tasks for today. 
<img width="282" alt="Screenshot 2022-06-01 at 7 03 24" src="https://user-images.githubusercontent.com/2179258/171331449-4f086825-eed7-4e8c-9f24-69294234d6da.png">
When "Import Today Tasks" pressed, the import fails, no tasks appear in the note. 

However, when I try to import all the tasks ("Import All Tasks"), the import works. 
<img width="255" alt="Screenshot 2022-06-01 at 7 05 01" src="https://user-images.githubusercontent.com/2179258/171331673-439b110f-e5de-4314-83d4-4a29e76b9f57.png">

This tells me that the API key works. 

**To Reproduce**
1. Go to Settings, add the API key
2. Click on "Import Todays Tasks"

**Expected behavior**
Expected behaviour is that the "Import Todays Tasks" succeeds, tasks are imported.

**Screenshots**
Screenshots added to the description.

**Other**
I wanted to check the logs, but I couldn't find them.

**Comment by FlohGro-dev** [comment]
Thanks for the very detailed report @gulyasm 

The craftx asset contained that bug and I updated it already..

Please re download the asset from here: https://github.com/FlohGro-dev/Craftist/releases/tag/0.8 and try again if it works 👍

**Comment by gulyasm** [comment]
Thanks, it did solve the issue!
