### ISSUE TITLE
Import Tasks From Linked Project Not Pulling In/Pushing Tasks

### ISSUE THREAD

**Issue by alsoknownaskaz** [FlohGro-dev/Craftist#58]
**Describe the bug**
**Amazing** product that you have created here! Just beginning to play with all of its functionality, however I am noticing that after linking the note to the Todoist project, even after the block appears showing the link, clicking to Import Tasks From Linked Project doesn't bring in any tasks currently in the Todoist project. Adding in tasks into the Craft note and then syncing, also does not seem to be pushing the tasks into the Todoist project. All other linking works fine, "Create Tasks from Selection," "Import Today's Tasks," etc. 

**To Reproduce**
1. Creating a new note
2. Clicking Link Note to Project (Link to Todoist project appears)
3. Clicking Import Tasks From Linked Project
4. The update banner shows "Craftist Inserted 0 Blocks)
5. I logged out and reset the API key just in case

**Expected behavior**
Expecting to see tasks import in by section, however I am not. Not sure if I am missing a step, however followed your video demo.

**Comment by FlohGro-dev** [comment]
Does import todays task work properly?

**Comment by alsoknownaskaz** [comment]
Yes, it does.

**Comment by FlohGro-dev** [comment]
This definitely should work like you described.
Is this related to a single project? → check other projects if it does not work with them (or e.g. the inbox)
Is it a shared project?

**Comment by alsoknownaskaz** [comment]
Of course it's working now. I logged out and back in with the API key and all good. So sorry to bother :)

**Comment by FlohGro-dev** [comment]
No problem - thanks for confirming it's working.. no idea what happened..
