### ISSUE TITLE
Login issue

### ISSUE THREAD

**Issue by samuthomi** [FlohGro-dev/Craftist#62]
Thanks for your brilliant plugin. I am using version 0.8.1 (beta)

I'm having a bit of a problem accessing Todoist with my  API token. I’ve tried issuing a new API token but I still get the same result. Could point me to what I may be doing wrong? or see if it also affects you.

<img width="291" alt="Screenshot 2022-12-08 at 07 33 45" src="https://user-images.githubusercontent.com/59906970/206358667-7bf059a4-e166-4527-818b-454b06dedcf3.png">

**Comment by FlohGro-dev** [comment]
I received that issue in a DM on Twitter, too.
I was able to reproduce it.

I expect there where some changes in the API that maybe are not reflected in the npm package or something like this.

I will look into it - you can't do anything right now..

Sorry for the inconvenience..

**Comment by FlohGro-dev** [comment]
Hi,

I released a fix for that issue: https://twitter.com/FlohGro/status/1602748138292498439?s=20&t=AVZTipIzVgadQIvWvcZ1ww

Download the new version from the repository: https://github.com/FlohGro-dev/Craftist


_______________________________

Kind regards,
FlohGro

: follow me on Twitter <https://twitter.com/FlohGro>
: check out my Website <https://flohgro.com/>
: support me on buymeacoffee <https://www.buymeacoffee.com/flohgro>

Some people expect an immediate response. I don’t. 
Feel free to respond when it works best for you. 
Let's make work more async <https://async.twist.com/> and less ASAP.

On 8. Dec 2022, at 05:43, Samson Kirigua ***@***.***> wrote:


I am having a bit of a problem accessing Todoist with my API token. I’ve tried issuing a new API token but I still get the same result.
If you have the time maybe you could point me to what I may be doing wrong? or see if it also affects you.
