### ISSUE TITLE
Link Note to Project

### ISSUE THREAD

**Issue by WillPlatnick** [FlohGro-dev/Craftist#9]
I use project notes in Craft to track my work on larger projects. Right now, crosslinking open tasks goes right to the Inbox. It'd be nice if I could link a note to a specific Project in Todoist, that way crosslink open tasks would create tasks in the right place in Todoist. It could also serve as the location for Import Tasks to draw from, rather than pulling everything.

**Comment by FlohGro-dev** [comment]
great idea :)
What would you excpect from such an action?
I can imagine different workflows / usecases (depending on the tools you use)

- link a Craft note to an existing project in todoist (this would need more on the UI side in the eXtension
- link a Craft note to a new project in todoist (e.g. create a new project in todoist with the name of the craft note
- if you use Drafts - I already built an action to crosslink a project between todoist and craft

Each of those usecases would enable to insert a block with information I need to retrieve / push tasks from / into the project

**Comment by WillPlatnick** [comment]
I would expect "link a Craft note to an existing project in todoist" to limit the scope of all Craftist actions to be limited to that project when you're in a note that is linked. Importing tasks would only import from that project. Crosslinking tasks would create the tasks in the linked Todoist project.

**Comment by FlohGro-dev** [comment]
thanks for the response - what I tried to describe is the "starting point" - how to link a note to a project. 
E.g.:
- "link a Craft note to an existing project in todoist" would work as follows
- press a button in the eXtension which fetches all projects from todoist displayed as buttons,.. (this is the tricky part and a lot more work than the other possibilities)
- then you select the project you want the note to link to from all existing projects.


importing only the tasks from the project or crosslinking them just in the linked project is all clear :)

**Comment by FlohGro-dev** [comment]
Hi @WillPlatnick I'm currenlty working on your request 
I integrated a new button which enables the user to link a note to an existing project in Todoist (this will prepend a block to the document which contains the link)
The create from selection / crosslink tasks button will now search for an existing link to a project and if one exists the tasks will be created in that project (if you link several todoist projects to one note the tasks will be created in the inbox)

Next I'll look into the importing of tasks of a linked project.
I could do this very roughly and just import every task in that project and e.g. append it to the end of the document, or i could put more work into it and only import tasks which are not already crosslinked between the note in Craft and Todoist.
What do you think?

my second question regarding the import of tasks is related to the location of the imported tasks.
I have two options:
- import the task to the current position (retrieved from the current selection in the editor)
- import the tasks and append them to the end of the document
What would you prefer?

**Comment by FlohGro-dev** [comment]
solved in release #12
